export type User = { id: number; username: string; role: string; os_user: string }
export type Profile = { id: number; slug: string; name: string; default_model?: string | null; is_default: boolean; hermes_home?: string; runner_id?: string }
export type Project = { slug: string; name: string; path: string; owner: string; role: string; visibility: 'private' | 'shared' }
export type Runner = { id: string; displayName: string; installed: boolean; path?: string | null; binary?: string | null; hasAdapter: boolean; detectionOnly: boolean; runnable: boolean; notes?: string }
export type ChatSession = { id: number; title: string; runner_id: string; profile_id?: number | null; profile_slug?: string | null; profile_name?: string | null; project_slug?: string | null; project_name?: string | null; visibility: 'private' | 'project'; updated_at?: string; task_id?: number | null; task_title?: string | null }
export type TaskStatus = 'todo' | 'doing' | 'review' | 'done'
export type Task = { id: number; project_slug: string | null; session_id: number | null; title: string; description: string; status: TaskStatus; assignee: string | null; created_by?: string | null; created_at: string; updated_at: string }
export type ActivityItem = { title: string; status: string; subagent: boolean }
export type ChatMessage = { id?: number; role: 'user' | 'system' | 'assistant' | 'error'; content: string; author?: string | null; run_id?: number | null; activity?: ActivityItem[]; created_at?: string }
export type RunEvent = { id: number; seq: number; type: string; run_id: number; session_id: number; project_id?: number | null; payload: Record<string, unknown>; created_at: string }
export type View = 'chat' | 'projects' | 'wiki' | 'artifacts' | 'tasks' | 'linc-projects' | 'profiles' | 'runners' | 'settings' | 'users'
export type FileEntry = { name: string; type: 'dir' | 'file'; size: number }
