import React from 'react'
import { createProject, inviteMember, listMembers, removeMember, deleteProject, type Member } from '../api/projects'
import { Dropdown } from '../components/ui/Dropdown'
import type { Project } from '../types'

export function ProjectsScreen({ token, projects, onActiveProject, onRefresh }: { token: string; projects: Project[]; onActiveProject: (p: Project) => void; onRefresh: () => Promise<void> }) {
  const [slug, setSlug] = React.useState('')
  const [name, setName] = React.useState('')
  const [visibility, setVisibility] = React.useState<'private' | 'shared'>('private')
  const [selected, setSelected] = React.useState<Project | null>(projects[0] || null)
  const [members, setMembers] = React.useState<Member[]>([])
  const [invite, setInvite] = React.useState('')
  const [error, setError] = React.useState('')
  React.useEffect(() => { if (selected) void listMembers(token, selected.slug).then(body => setMembers(body.members)).catch(() => setMembers([])) }, [selected?.slug, token])
  async function create(event: React.FormEvent) { event.preventDefault(); setError(''); try { const p = await createProject(token, { slug, name: name || slug, visibility }); setSlug(''); setName(''); setSelected(p); onActiveProject(p); await onRefresh() } catch (err) { setError(String(err)) } }
  async function member(action: 'invite' | 'remove') { if (!selected) return; try { action === 'invite' ? await inviteMember(token, selected.slug, invite) : await removeMember(token, selected.slug, invite); const body = await listMembers(token, selected.slug); setMembers(body.members); await onRefresh() } catch (err) { setError(String(err)) } }
  async function removeProject() { if (!selected) return; if (!window.confirm(`Delete project "${selected.name}"? Its files, chats and tasks will be removed. This cannot be undone.`)) return; setError(''); try { await deleteProject(token, selected.slug); setSelected(null); await onRefresh() } catch (err) { setError(String(err)) } }
  return <section className="projects-view"><div className="panel project-list-panel"><div className="panel-head"><h3>Projects</h3><span>{projects.length}</span></div>{projects.map(project => <button className={`project-card ${selected?.slug === project.slug ? 'active' : ''}`} key={project.slug} onClick={() => { setSelected(project); onActiveProject(project) }}><strong>{project.name}</strong><small>{project.slug}</small><span>{project.visibility} · {project.role}</span></button>)}</div><div className="panel project-actions-panel"><div className="panel-head"><h3>Create project</h3><span>team mode</span></div><form className="stack-form" onSubmit={create}><label>Slug<input value={slug} onChange={e => setSlug(e.target.value)} /></label><label>Name<input value={name} onChange={e => setName(e.target.value)} /></label><label>Visibility<Dropdown value={visibility} onChange={v => setVisibility(v as 'private' | 'shared')} options={[{ value: 'private', label: 'Private' }, { value: 'shared', label: 'Shared' }]} /></label><button className="primary-button" disabled={!slug}>Create</button></form><div className="divider" /><div className="panel-head"><h3>Members</h3><span>{selected?.slug || 'none'}</span></div>{members.map(m => <p className="member-row" key={m.username}><strong>{m.username}</strong><span>{m.role}</span></p>)}<div className="stack-form"><label>User<input value={invite} onChange={e => setInvite(e.target.value)} /></label><div className="button-row"><button disabled={!selected || !invite} onClick={() => void member('invite')}>Invite</button><button disabled={!selected || !invite} onClick={() => void member('remove')}>Remove</button></div></div>{selected?.role === 'owner' && <><div className="divider" /><div className="danger-zone"><div><strong>Delete project</strong><small className="muted"> Removes files, chats &amp; tasks. Cannot be undone.</small></div><button className="ghost-button danger" onClick={() => void removeProject()}>Delete “{selected.name}”</button></div></>}{error && <p className="error-text">{error}</p>}</div></section>
}
