"""Wiki-as-memory helpers: the automatic project log (Layer 1) and parsing of
the agent's Save-to-wiki note draft (Layer 2). Kept free of any agent/runner
dependency so it is unit-testable in isolation."""
from __future__ import annotations

import json
import re
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

# Layer 1 — the summarize prompt the worker sends after a successful run.
SUMMARIZE_PROMPT = (
    "In one sentence, summarize what you just did, for the project log. "
    "Output only the sentence — no preamble, no markdown, no quotes."
)


def format_log_entry(when: datetime, author: str, summary: str, task_title: str | None = None) -> str:
    line = f"- {when:%H:%M} · {author} — {summary.strip()}"
    if task_title:
        line += f" ([[task: {task_title}]])"
    return line


def _insert_entry(existing: str, heading: str, entry: str) -> str:
    """Newest day section on top; newest entry on top within its day."""
    if heading in existing:
        lines = existing.split("\n")
        idx = lines.index(heading)
        lines.insert(idx + 1, entry)
        return "\n".join(lines)
    block = f"{heading}\n{entry}\n"
    if existing.strip():
        return f"{block}\n{existing.lstrip()}"
    return f"# Project log\n\n{block}"


def append_log_entry(wiki_root: Path, when: datetime, author: str, summary: str, task_title: str | None = None) -> None:
    log = Path(wiki_root) / "log.md"
    existing = log.read_text(encoding="utf-8") if log.exists() else ""
    new_text = _insert_entry(existing, f"## {when:%Y-%m-%d}", format_log_entry(when, author, summary, task_title))
    log.parent.mkdir(parents=True, exist_ok=True)
    log.write_text(new_text, encoding="utf-8")


def _note_title(text: str, path: Path) -> str:
    """First `# ` heading, else the filename humanized."""
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ").replace("_", " ").strip()


def _note_summary(text: str) -> str:
    """One line for the catalog: frontmatter `description:` if present, else the
    first non-blank, non-heading line. Truncated."""
    text = text.replace("\r\n", "\n")
    fm = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if fm:
        m = re.search(r"^description:\s*(.+)$", fm.group(1), re.MULTILINE)
        if m:
            return m.group(1).strip().strip("\"'")[:140]
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("---"):
            continue
        return s[:140]
    return ""


def rebuild_index(wiki_root: Path) -> None:
    """Regenerate wiki/index.md — a catalog (title + one-line summary) of the
    project's notes so an agent can see what exists without reading every file.
    Excludes index.md, log.md, and the graphify-out/ build dir. No-op if the wiki
    directory does not exist."""
    root = Path(wiki_root)
    if not root.is_dir():
        return
    entries: list[tuple[str, str, str]] = []
    for md in sorted(root.rglob("*.md")):
        rel = md.relative_to(root).as_posix()
        if rel in ("index.md", "log.md") or rel.endswith("/log.md") or rel.startswith("graphify-out/"):
            continue
        try:
            text = md.read_text(encoding="utf-8")
        except OSError:
            continue
        entries.append((rel, _note_title(text, md), _note_summary(text)))
    body = ["# Wiki index", "", "<!-- Auto-generated by Hive OS. Catalog of this project's notes. -->", ""]
    if entries:
        for rel, title, summary in entries:
            body.append(f"- [{title}]({rel})" + (f" — {summary}" if summary else ""))
    else:
        body.append("_No notes yet._")
    (root / "index.md").write_text("\n".join(body) + "\n", encoding="utf-8")


HIVE_PREAMBLE_MARKER = "[Hive OS context]"


def build_run_preamble(project_name: str | None, project_slug: str | None, wiki_root: Path | None) -> str | None:
    """Context block prepended to the FIRST prompt of an agent's ACP session,
    telling it it runs inside Hive OS and how to consult the project's wiki memory.
    Runner-agnostic plain text. Returns None when there is no project to anchor to."""
    if not project_name:
        return None
    lines = [
        HIVE_PREAMBLE_MARKER,
        f'You are running inside Hive OS. Project: "{project_name}" (slug: {project_slug or "-"}).',
        "Your working directory is this project — files you read and write are its files.",
    ]
    root = Path(wiki_root) if wiki_root is not None else None
    if root is not None and root.is_dir():
        if (root / "index.md").exists():
            lines += [
                "",
                "This project keeps durable memory in wiki/. Before answering anything that "
                "builds on past work, scan wiki/index.md (a catalog of notes) and open the "
                "relevant ones. Use that context when it applies; ignore it when it doesn't.",
            ]
        else:
            lines += [
                "",
                "This project keeps durable memory in wiki/. Before answering anything that "
                "builds on past work, scan the wiki/ folder and open the relevant notes.",
            ]
        if (root / "graphify-out" / "graph.json").exists() and shutil.which("graphify"):
            lines.append(
                'Fast lookup: `graphify query "<question>" --graph wiki/graphify-out/graph.json --budget 2000`.'
            )
        lines += [
            "",
            'Durable notes are curated by the human via "Save to wiki" — read wiki/ freely, '
            "but don't create notes yourself.",
        ]
    else:
        lines += ["", "A wiki/ folder will hold this project's durable memory as it grows."]
    return "\n".join(lines)


def build_draft_prompt(existing_notes: list[dict[str, Any]]) -> str:
    """Prompt the (already-context-loaded) agent to distill THIS conversation into
    a wiki note, cross-checked against existing notes. log.md is excluded — it is
    the running journal, not a reference note."""
    refs = []
    for n in existing_notes:
        path = str(n.get("path") or "")
        if not path or path == "log.md" or path.endswith("/log.md"):
            continue
        first = (n.get("content") or "").strip().splitlines()
        refs.append(f"- {path}: {first[0] if first else ''}")
    refs_block = "\n".join(refs) if refs else "(none yet)"
    return (
        "Based on our conversation above, produce a single wiki note that captures "
        "what is worth keeping — focused on what is relevant to THIS project and what "
        "we can adopt, not a transcript.\n\n"
        "Cross-check it against the existing notes listed below. If it overlaps one, "
        "say which and what is genuinely new; if it contradicts one, flag the conflict.\n\n"
        f"Existing notes (path: first line):\n{refs_block}\n\n"
        "Reply with ONLY a fenced ```json block, no other text, shaped exactly:\n"
        "```json\n"
        "{\n"
        '  "title": "Short title",\n'
        '  "path": "<topic-folder>/<slug>.md",\n'
        '  "body": "# Title\\n\\nMarkdown body with [[links]] to related notes.",\n'
        '  "related": ["existing/path.md"],\n'
        '  "conflicts": ["one line per conflict, or empty"],\n'
        '  "action": "new" or "merge",\n'
        '  "target": "existing/path.md if action is merge, else null"\n'
        "}\n"
        "```"
    )


def parse_note_draft(text: str) -> dict[str, Any]:
    m = re.search(r"```json\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        try:
            data = json.loads(m.group(1))
            return {
                "title": str(data.get("title") or "Untitled"),
                "path": str(data.get("path") or "notes/untitled.md"),
                "body": str(data.get("body") or ""),
                "related": [str(x) for x in (data.get("related") or [])],
                "conflicts": [str(x) for x in (data.get("conflicts") or [])],
                "action": "merge" if str(data.get("action")) == "merge" else "new",
                "target": (str(data["target"]) if data.get("target") else None),
                "unparsed": False,
            }
        except (json.JSONDecodeError, ValueError, TypeError):
            pass
    return {
        "title": "Draft note", "path": "notes/draft.md", "body": text.strip(),
        "related": [], "conflicts": [], "action": "new", "target": None, "unparsed": True,
    }
